### ISSUE TITLE
一会儿就闪退了?

### ISSUE THREAD

**Issue by zsq2010** [JamesWone/SmartQQ#1]
刚登录 就叫我去先w.qq.com,说会恢复...老大我q 979719833

**Comment by jamestack** [comment]
我刚测试了，可以正常登陆并收发消息的。

**Comment by weaming** [comment]
不能登录
index out of range

```
goroutine 1 [running]:
weaming/qqbot/vendor/github.com/JamesWone/SmartQQ.(*QClient).Run(0xc04204a1c0)
        D:/go/src/weaming/qqbot/vendor/github.com/JamesWone/SmartQQ/smartqq.go:250 +0x1909
main.main()
        D:/Go/src/weaming/qqbot/main.go:69 +0x186
exit status 2
```
